# NOTE: Currently only docs are deployed, maybe a webpage could be added in the future?
name: cd
on:
  push:
    branches:
      - main
permissions:
  contents: read 
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build docs
        run: zig build docs

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        id: docs
        with:
          path: zig-out/docs/

  # Deploy docs
  deploy:
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to github pages
        id: docs
        uses: actions/deploy-pages@v4


